// DO NOT EDIT: This file is autogenerated via the builtin command.

package testing

import (
	flux "github.com/influxdata/flux"
	ast "github.com/influxdata/flux/ast"
)

func init() {
	flux.RegisterPackage(pkgAST)
}

var pkgAST = &ast.Package{
	BaseNode: ast.BaseNode{
		Errors: nil,
		Loc:    nil,
	},
	Files: []*ast.File{&ast.File{
		BaseNode: ast.BaseNode{
			Errors: nil,
			Loc: &ast.SourceLocation{
				End: ast.Position{
					Column: 61,
					Line:   4,
				},
				File:   "test.flux",
				Source: "package testing\n\ntest = (name,input,want,test) =>\n    assertEquals(name: name, got: input|>test(), want: want)",
				Start: ast.Position{
					Column: 1,
					Line:   1,
				},
			},
		},
		Body: []ast.Statement{&ast.VariableAssignment{
			BaseNode: ast.BaseNode{
				Errors: nil,
				Loc: &ast.SourceLocation{
					End: ast.Position{
						Column: 61,
						Line:   4,
					},
					File:   "test.flux",
					Source: "test = (name,input,want,test) =>\n    assertEquals(name: name, got: input|>test(), want: want)",
					Start: ast.Position{
						Column: 1,
						Line:   3,
					},
				},
			},
			ID: &ast.Identifier{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 5,
							Line:   3,
						},
						File:   "test.flux",
						Source: "test",
						Start: ast.Position{
							Column: 1,
							Line:   3,
						},
					},
				},
				Name: "test",
			},
			Init: &ast.FunctionExpression{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 61,
							Line:   4,
						},
						File:   "test.flux",
						Source: "(name,input,want,test) =>\n    assertEquals(name: name, got: input|>test(), want: want)",
						Start: ast.Position{
							Column: 8,
							Line:   3,
						},
					},
				},
				Body: &ast.CallExpression{
					Arguments: []ast.Expression{&ast.ObjectExpression{
						BaseNode: ast.BaseNode{
							Errors: nil,
							Loc: &ast.SourceLocation{
								End: ast.Position{
									Column: 60,
									Line:   4,
								},
								File:   "test.flux",
								Source: "name: name, got: input|>test(), want: want",
								Start: ast.Position{
									Column: 18,
									Line:   4,
								},
							},
						},
						Properties: []*ast.Property{&ast.Property{
							BaseNode: ast.BaseNode{
								Errors: nil,
								Loc: &ast.SourceLocation{
									End: ast.Position{
										Column: 28,
										Line:   4,
									},
									File:   "test.flux",
									Source: "name: name",
									Start: ast.Position{
										Column: 18,
										Line:   4,
									},
								},
							},
							Key: &ast.Identifier{
								BaseNode: ast.BaseNode{
									Errors: nil,
									Loc: &ast.SourceLocation{
										End: ast.Position{
											Column: 22,
											Line:   4,
										},
										File:   "test.flux",
										Source: "name",
										Start: ast.Position{
											Column: 18,
											Line:   4,
										},
									},
								},
								Name: "name",
							},
							Value: &ast.Identifier{
								BaseNode: ast.BaseNode{
									Errors: nil,
									Loc: &ast.SourceLocation{
										End: ast.Position{
											Column: 28,
											Line:   4,
										},
										File:   "test.flux",
										Source: "name",
										Start: ast.Position{
											Column: 24,
											Line:   4,
										},
									},
								},
								Name: "name",
							},
						}, &ast.Property{
							BaseNode: ast.BaseNode{
								Errors: nil,
								Loc: &ast.SourceLocation{
									End: ast.Position{
										Column: 48,
										Line:   4,
									},
									File:   "test.flux",
									Source: "got: input|>test()",
									Start: ast.Position{
										Column: 30,
										Line:   4,
									},
								},
							},
							Key: &ast.Identifier{
								BaseNode: ast.BaseNode{
									Errors: nil,
									Loc: &ast.SourceLocation{
										End: ast.Position{
											Column: 33,
											Line:   4,
										},
										File:   "test.flux",
										Source: "got",
										Start: ast.Position{
											Column: 30,
											Line:   4,
										},
									},
								},
								Name: "got",
							},
							Value: &ast.PipeExpression{
								Argument: &ast.Identifier{
									BaseNode: ast.BaseNode{
										Errors: nil,
										Loc: &ast.SourceLocation{
											End: ast.Position{
												Column: 40,
												Line:   4,
											},
											File:   "test.flux",
											Source: "input",
											Start: ast.Position{
												Column: 35,
												Line:   4,
											},
										},
									},
									Name: "input",
								},
								BaseNode: ast.BaseNode{
									Errors: nil,
									Loc: &ast.SourceLocation{
										End: ast.Position{
											Column: 48,
											Line:   4,
										},
										File:   "test.flux",
										Source: "input|>test()",
										Start: ast.Position{
											Column: 35,
											Line:   4,
										},
									},
								},
								Call: &ast.CallExpression{
									Arguments: nil,
									BaseNode: ast.BaseNode{
										Errors: nil,
										Loc: &ast.SourceLocation{
											End: ast.Position{
												Column: 48,
												Line:   4,
											},
											File:   "test.flux",
											Source: "test()",
											Start: ast.Position{
												Column: 42,
												Line:   4,
											},
										},
									},
									Callee: &ast.Identifier{
										BaseNode: ast.BaseNode{
											Errors: nil,
											Loc: &ast.SourceLocation{
												End: ast.Position{
													Column: 46,
													Line:   4,
												},
												File:   "test.flux",
												Source: "test",
												Start: ast.Position{
													Column: 42,
													Line:   4,
												},
											},
										},
										Name: "test",
									},
								},
							},
						}, &ast.Property{
							BaseNode: ast.BaseNode{
								Errors: nil,
								Loc: &ast.SourceLocation{
									End: ast.Position{
										Column: 60,
										Line:   4,
									},
									File:   "test.flux",
									Source: "want: want",
									Start: ast.Position{
										Column: 50,
										Line:   4,
									},
								},
							},
							Key: &ast.Identifier{
								BaseNode: ast.BaseNode{
									Errors: nil,
									Loc: &ast.SourceLocation{
										End: ast.Position{
											Column: 54,
											Line:   4,
										},
										File:   "test.flux",
										Source: "want",
										Start: ast.Position{
											Column: 50,
											Line:   4,
										},
									},
								},
								Name: "want",
							},
							Value: &ast.Identifier{
								BaseNode: ast.BaseNode{
									Errors: nil,
									Loc: &ast.SourceLocation{
										End: ast.Position{
											Column: 60,
											Line:   4,
										},
										File:   "test.flux",
										Source: "want",
										Start: ast.Position{
											Column: 56,
											Line:   4,
										},
									},
								},
								Name: "want",
							},
						}},
					}},
					BaseNode: ast.BaseNode{
						Errors: nil,
						Loc: &ast.SourceLocation{
							End: ast.Position{
								Column: 61,
								Line:   4,
							},
							File:   "test.flux",
							Source: "assertEquals(name: name, got: input|>test(), want: want)",
							Start: ast.Position{
								Column: 5,
								Line:   4,
							},
						},
					},
					Callee: &ast.Identifier{
						BaseNode: ast.BaseNode{
							Errors: nil,
							Loc: &ast.SourceLocation{
								End: ast.Position{
									Column: 17,
									Line:   4,
								},
								File:   "test.flux",
								Source: "assertEquals",
								Start: ast.Position{
									Column: 5,
									Line:   4,
								},
							},
						},
						Name: "assertEquals",
					},
				},
				Params: []*ast.Property{&ast.Property{
					BaseNode: ast.BaseNode{
						Errors: nil,
						Loc: &ast.SourceLocation{
							End: ast.Position{
								Column: 13,
								Line:   3,
							},
							File:   "test.flux",
							Source: "name",
							Start: ast.Position{
								Column: 9,
								Line:   3,
							},
						},
					},
					Key: &ast.Identifier{
						BaseNode: ast.BaseNode{
							Errors: nil,
							Loc: &ast.SourceLocation{
								End: ast.Position{
									Column: 13,
									Line:   3,
								},
								File:   "test.flux",
								Source: "name",
								Start: ast.Position{
									Column: 9,
									Line:   3,
								},
							},
						},
						Name: "name",
					},
					Value: nil,
				}, &ast.Property{
					BaseNode: ast.BaseNode{
						Errors: nil,
						Loc: &ast.SourceLocation{
							End: ast.Position{
								Column: 19,
								Line:   3,
							},
							File:   "test.flux",
							Source: "input",
							Start: ast.Position{
								Column: 14,
								Line:   3,
							},
						},
					},
					Key: &ast.Identifier{
						BaseNode: ast.BaseNode{
							Errors: nil,
							Loc: &ast.SourceLocation{
								End: ast.Position{
									Column: 19,
									Line:   3,
								},
								File:   "test.flux",
								Source: "input",
								Start: ast.Position{
									Column: 14,
									Line:   3,
								},
							},
						},
						Name: "input",
					},
					Value: nil,
				}, &ast.Property{
					BaseNode: ast.BaseNode{
						Errors: nil,
						Loc: &ast.SourceLocation{
							End: ast.Position{
								Column: 24,
								Line:   3,
							},
							File:   "test.flux",
							Source: "want",
							Start: ast.Position{
								Column: 20,
								Line:   3,
							},
						},
					},
					Key: &ast.Identifier{
						BaseNode: ast.BaseNode{
							Errors: nil,
							Loc: &ast.SourceLocation{
								End: ast.Position{
									Column: 24,
									Line:   3,
								},
								File:   "test.flux",
								Source: "want",
								Start: ast.Position{
									Column: 20,
									Line:   3,
								},
							},
						},
						Name: "want",
					},
					Value: nil,
				}, &ast.Property{
					BaseNode: ast.BaseNode{
						Errors: nil,
						Loc: &ast.SourceLocation{
							End: ast.Position{
								Column: 29,
								Line:   3,
							},
							File:   "test.flux",
							Source: "test",
							Start: ast.Position{
								Column: 25,
								Line:   3,
							},
						},
					},
					Key: &ast.Identifier{
						BaseNode: ast.BaseNode{
							Errors: nil,
							Loc: &ast.SourceLocation{
								End: ast.Position{
									Column: 29,
									Line:   3,
								},
								File:   "test.flux",
								Source: "test",
								Start: ast.Position{
									Column: 25,
									Line:   3,
								},
							},
						},
						Name: "test",
					},
					Value: nil,
				}},
			},
		}},
		Imports: nil,
		Name:    "test.flux",
		Package: &ast.PackageClause{
			BaseNode: ast.BaseNode{
				Errors: nil,
				Loc: &ast.SourceLocation{
					End: ast.Position{
						Column: 16,
						Line:   1,
					},
					File:   "test.flux",
					Source: "package testing",
					Start: ast.Position{
						Column: 1,
						Line:   1,
					},
				},
			},
			Name: &ast.Identifier{
				BaseNode: ast.BaseNode{
					Errors: nil,
					Loc: &ast.SourceLocation{
						End: ast.Position{
							Column: 16,
							Line:   1,
						},
						File:   "test.flux",
						Source: "testing",
						Start: ast.Position{
							Column: 9,
							Line:   1,
						},
					},
				},
				Name: "testing",
			},
		},
	}},
	Package: "testing",
	Path:    "testing",
}
