// DO NOT EDIT: This file is autogenerated via the builtin command.

package pkg

import (
	_ "github.com/influxdata/flux/functions/pkg/influxdb"
	_ "github.com/influxdata/flux/functions/pkg/influxdb/telegraf"
	_ "github.com/influxdata/flux/functions/pkg/testing"
)
